<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 4.9.1
 */

/**
 * Database `webschoolprojecttest`
 */

/* `webschoolprojecttest`.`student` */
$student = array(
  array('ID' => '1','Mr of Mrs' => 'นาย','Name' => 'ไก่','Lastname' => 'ย่าง','Class' => '1','Classnumber' => '1','Number' => '1'),
  array('ID' => '2','Mr of Mrs' => 'นาย','Name' => 'ไก่','Lastname' => 'ทอด','Class' => '1','Classnumber' => '1','Number' => '2'),
  array('ID' => '3','Mr of Mrs' => 'นางสาว','Name' => 'ฟ้า','Lastname' => 'สีคราม','Class' => '1','Classnumber' => '1','Number' => '3'),
  array('ID' => '4','Mr of Mrs' => 'นางสาว','Name' => 'ไพร','Lastname' => 'พงไพร','Class' => '1','Classnumber' => '1','Number' => '4'),
  array('ID' => '5','Mr of Mrs' => 'นาย','Name' => 'ไก่','Lastname' => 'ขัน','Class' => '1','Classnumber' => '1','Number' => '5'),
  array('ID' => '6','Mr of Mrs' => 'นาย','Name' => 'ไก่','Lastname' => 'ร้อง','Class' => '1','Classnumber' => '1','Number' => '6'),
  array('ID' => '7','Mr of Mrs' => 'นางสาว','Name' => 'ปลายฟ้า','Lastname' => 'สีคราม','Class' => '1','Classnumber' => '1','Number' => '7'),
  array('ID' => '8','Mr of Mrs' => 'นางสาว','Name' => 'มาลัย','Lastname' => 'สามชาย','Class' => '1','Classnumber' => '1','Number' => '8'),
  array('ID' => '9','Mr of Mrs' => 'นาย','Name' => 'ไชย','Lastname' => 'จระเข้','Class' => '1','Classnumber' => '1','Number' => '9'),
  array('ID' => '10','Mr of Mrs' => 'นางสาว','Name' => 'มะลิ','Lastname' => 'ซ่อนกลิ่น','Class' => '1','Classnumber' => '1','Number' => '10'),
  array('ID' => '11','Mr of Mrs' => 'นาย','Name' => 'มาลัย','Lastname' => 'มาดี','Class' => '1','Classnumber' => '2','Number' => '1'),
  array('ID' => '12','Mr of Mrs' => 'นาย','Name' => 'มานพ','Lastname' => 'สมสมัย','Class' => '1','Classnumber' => '2','Number' => '2'),
  array('ID' => '13','Mr of Mrs' => 'นาย','Name' => 'ต้นกล้า','Lastname' => 'ท้องนา','Class' => '1','Classnumber' => '2','Number' => '3'),
  array('ID' => '14','Mr of Mrs' => 'นาย','Name' => 'ต้นข้าว','Lastname' => 'ท้องนา','Class' => '1','Classnumber' => '2','Number' => '4'),
  array('ID' => '15','Mr of Mrs' => 'นาย','Name' => 'ใบชา','Lastname' => 'ต้นชา','Class' => '1','Classnumber' => '2','Number' => '5'),
  array('ID' => '16','Mr of Mrs' => 'นางสาว','Name' => 'พานทอง','Lastname' => 'สายสมร','Class' => '1','Classnumber' => '2','Number' => '6'),
  array('ID' => '17','Mr of Mrs' => 'นางสาว','Name' => 'ราตรี','Lastname' => 'ค่ำคืน','Class' => '1','Classnumber' => '2','Number' => '7'),
  array('ID' => '18','Mr of Mrs' => 'นางสาว','Name' => 'สายใจ','Lastname' => 'สบายดี','Class' => '1','Classnumber' => '2','Number' => '8'),
  array('ID' => '19','Mr of Mrs' => 'นางสาว','Name' => 'พานพุ่ม','Lastname' => 'อุดมสมบูรณ์','Class' => '1','Classnumber' => '2','Number' => '9'),
  array('ID' => '20','Mr of Mrs' => 'นางสาว','Name' => 'ราตรี','Lastname' => 'อนาคตดี','Class' => '1','Classnumber' => '2','Number' => '10'),
  array('ID' => '21','Mr of Mrs' => 'นาย','Name' => 'อนาคตใหม่','Lastname' => 'ชาติเจริญ','Class' => '1','Classnumber' => '3','Number' => '1'),
  array('ID' => '22','Mr of Mrs' => 'นาย','Name' => 'ประหยัด','Lastname' => 'สมชื่อ','Class' => '1','Classnumber' => '3','Number' => '2'),
  array('ID' => '23','Mr of Mrs' => 'นาย','Name' => 'เกียรตินาคิน','Lastname' => 'พาณิชย์','Class' => '1','Classnumber' => '3','Number' => '3'),
  array('ID' => '24','Mr of Mrs' => 'นาย','Name' => 'เกียรติพาคิน','Lastname' => 'พาณิชย์','Class' => '1','Classnumber' => '3','Number' => '4'),
  array('ID' => '25','Mr of Mrs' => 'นาย','Name' => 'ชาติชาย','Lastname' => 'ประเทศราช','Class' => '1','Classnumber' => '3','Number' => '5'),
  array('ID' => '26','Mr of Mrs' => 'นางสาว','Name' => 'สมใจ','Lastname' => 'มาลัยดี','Class' => '1','Classnumber' => '3','Number' => '6'),
  array('ID' => '27','Mr of Mrs' => 'นางสาว','Name' => 'ยิ้มดี','Lastname' => 'พราวเสน่','Class' => '1','Classnumber' => '3','Number' => '7'),
  array('ID' => '28','Mr of Mrs' => 'นางสาว','Name' => 'ปรายดาว','Lastname' => 'ฟ้าคราม','Class' => '1','Classnumber' => '3','Number' => '8'),
  array('ID' => '29','Mr of Mrs' => 'นางสาว','Name' => 'ปรายฟ้า','Lastname' => 'ราชวิถี','Class' => '1','Classnumber' => '3','Number' => '9'),
  array('ID' => '30','Mr of Mrs' => 'นางสาว','Name' => 'ลาวดี','Lastname' => 'มีปรีดา','Class' => '1','Classnumber' => '3','Number' => '10'),
  array('ID' => '31','Mr of Mrs' => 'นาย','Name' => 'ธงชาติ','Lastname' => 'ไทยสยาม','Class' => '2','Classnumber' => '1','Number' => '1'),
  array('ID' => '32','Mr of Mrs' => 'นาย','Name' => 'องค์ชาย','Lastname' => 'ลายทหาร','Class' => '2','Classnumber' => '1','Number' => '2'),
  array('ID' => '33','Mr of Mrs' => 'นาย','Name' => 'มาดี','Lastname' => 'ศรีชาติ','Class' => '2','Classnumber' => '1','Number' => '3'),
  array('ID' => '34','Mr of Mrs' => 'นาย','Name' => 'มานพ','Lastname' => 'ทรงไชย','Class' => '2','Classnumber' => '1','Number' => '4'),
  array('ID' => '35','Mr of Mrs' => 'นาย','Name' => 'ธงชัย','Lastname' => 'ประภาษดี','Class' => '2','Classnumber' => '1','Number' => '5'),
  array('ID' => '36','Mr of Mrs' => 'นางสาว','Name' => 'สายน้ำ','Lastname' => 'ธารน้ำใจ','Class' => '2','Classnumber' => '1','Number' => '6'),
  array('ID' => '37','Mr of Mrs' => 'นางสาว','Name' => 'พราวดี','Lastname' => 'ปรีดา','Class' => '2','Classnumber' => '1','Number' => '7'),
  array('ID' => '38','Mr of Mrs' => 'นางสาว','Name' => 'กรกช','Lastname' => 'เขียวขจี','Class' => '2','Classnumber' => '1','Number' => '8'),
  array('ID' => '39','Mr of Mrs' => 'นางสาว','Name' => 'ใหม่','Lastname' => 'คลายดารา','Class' => '2','Classnumber' => '1','Number' => '9'),
  array('ID' => '40','Mr of Mrs' => 'นางสาว','Name' => 'พานทอง','Lastname' => 'สงบใจ','Class' => '2','Classnumber' => '1','Number' => '10'),
  array('ID' => '41','Mr of Mrs' => 'นาย','Name' => 'พละ','Lastname' => 'ศึกษา','Class' => '2','Classnumber' => '2','Number' => '1'),
  array('ID' => '42','Mr of Mrs' => 'นาย','Name' => 'ศีลดี','Lastname' => 'มีสุข','Class' => '2','Classnumber' => '2','Number' => '2'),
  array('ID' => '43','Mr of Mrs' => 'นาย','Name' => 'พงไพร','Lastname' => 'เขียวขจี','Class' => '2','Classnumber' => '2','Number' => '3'),
  array('ID' => '44','Mr of Mrs' => 'นาย','Name' => 'หินผา','Lastname' => 'ตรึงตรา','Class' => '2','Classnumber' => '2','Number' => '4'),
  array('ID' => '45','Mr of Mrs' => 'นาย','Name' => 'ทระนง','Lastname' => 'สมชาติ','Class' => '2','Classnumber' => '2','Number' => '5'),
  array('ID' => '46','Mr of Mrs' => 'นาย','Name' => 'สงขรา','Lastname' => 'ชงชาติมี','Class' => '2','Classnumber' => '2','Number' => '6'),
  array('ID' => '47','Mr of Mrs' => 'นาย','Name' => 'กรนัย','Lastname' => 'กามสิน','Class' => '2','Classnumber' => '2','Number' => '7'),
  array('ID' => '48','Mr of Mrs' => 'นาย','Name' => 'สุทธิ ','Lastname' => 'กายนา','Class' => '2','Classnumber' => '2','Number' => '8'),
  array('ID' => '49','Mr of Mrs' => 'นาย','Name' => 'สุทันดา','Lastname' => 'ทาสี','Class' => '2','Classnumber' => '2','Number' => '9'),
  array('ID' => '50','Mr of Mrs' => 'นาย','Name' => 'สุทิน','Lastname' => 'ยิ่งดี','Class' => '2','Classnumber' => '2','Number' => '10'),
  array('ID' => '51','Mr of Mrs' => 'นาย','Name' => 'สาสุน','Lastname' => 'อุ่นออม','Class' => '2','Classnumber' => '3','Number' => '1'),
  array('ID' => '52','Mr of Mrs' => 'นาย','Name' => 'สูทิตา','Lastname' => 'กามาระ','Class' => '2','Classnumber' => '3','Number' => '2'),
  array('ID' => '53','Mr of Mrs' => 'นาย','Name' => 'กานทา','Lastname' => 'นามมี','Class' => '2','Classnumber' => '3','Number' => '3'),
  array('ID' => '54','Mr of Mrs' => 'นาย','Name' => 'กันทิน','Lastname' => 'ทุกทาน','Class' => '2','Classnumber' => '3','Number' => '4'),
  array('ID' => '55','Mr of Mrs' => 'นาย','Name' => 'กุณซือ','Lastname' => 'ฮองกง','Class' => '2','Classnumber' => '3','Number' => '5'),
  array('ID' => '56','Mr of Mrs' => 'นางสาว','Name' => 'กานทินดา','Lastname' => 'สามีดี','Class' => '2','Classnumber' => '3','Number' => '6'),
  array('ID' => '57','Mr of Mrs' => 'นางสาว','Name' => 'กันทิดา','Lastname' => 'สินดี','Class' => '2','Classnumber' => '3','Number' => '7'),
  array('ID' => '58','Mr of Mrs' => 'นางสาว','Name' => 'กิววะณี','Lastname' => 'สีทิน','Class' => '2','Classnumber' => '3','Number' => '8'),
  array('ID' => '59','Mr of Mrs' => 'นางสาว','Name' => 'กืนนา','Lastname' => 'สามหมื่น','Class' => '2','Classnumber' => '3','Number' => '9'),
  array('ID' => '60','Mr of Mrs' => 'นางสาว','Name' => 'ปานิดา','Lastname' => 'นองสิน','Class' => '2','Classnumber' => '3','Number' => '10'),
  array('ID' => '61','Mr of Mrs' => 'นาย','Name' => 'กัมมี','Lastname' => 'มันกาล','Class' => '3','Classnumber' => '1','Number' => '1'),
  array('ID' => '62','Mr of Mrs' => 'นาย','Name' => 'ครึกศร','Lastname' => 'ทรนง','Class' => '3','Classnumber' => '1','Number' => '2'),
  array('ID' => '63','Mr of Mrs' => 'นาย','Name' => 'คนิยา','Lastname' => 'สารมี','Class' => '3','Classnumber' => '1','Number' => '3'),
  array('ID' => '64','Mr of Mrs' => 'นาย','Name' => 'วาที','Lastname' => 'ทีโอมา','Class' => '3','Classnumber' => '1','Number' => '4'),
  array('ID' => '65','Mr of Mrs' => 'นาย','Name' => 'วานิน','Lastname' => 'ทาราทิป','Class' => '3','Classnumber' => '1','Number' => '5'),
  array('ID' => '66','Mr of Mrs' => 'นางสาว','Name' => 'ปัททาธิ','Lastname' => 'สินมา','Class' => '3','Classnumber' => '1','Number' => '6'),
  array('ID' => '67','Mr of Mrs' => 'นางสาว','Name' => 'ปะทิน','Lastname' => 'กินมา','Class' => '3','Classnumber' => '1','Number' => '7'),
  array('ID' => '68','Mr of Mrs' => 'นางสาว','Name' => 'ดาริน','Lastname' => 'ดีแน่','Class' => '3','Classnumber' => '1','Number' => '8'),
  array('ID' => '69','Mr of Mrs' => 'นางสาว','Name' => 'มารีนา','Lastname' => 'สามศรี','Class' => '3','Classnumber' => '1','Number' => '9'),
  array('ID' => '70','Mr of Mrs' => 'นางสาว','Name' => 'ดลธิดา','Lastname' => 'กาลศรี','Class' => '3','Classnumber' => '1','Number' => '10'),
  array('ID' => '71','Mr of Mrs' => 'นาย','Name' => 'ปรายุ','Lastname' => 'ยุยงทน','Class' => '3','Classnumber' => '2','Number' => '1'),
  array('ID' => '72','Mr of Mrs' => 'นาย','Name' => 'ปรานี','Lastname' => 'ทินนาวุต','Class' => '3','Classnumber' => '2','Number' => '2'),
  array('ID' => '73','Mr of Mrs' => 'นาย','Name' => 'ปับปัย','Lastname' => 'ทุรราดิน','Class' => '3','Classnumber' => '2','Number' => '3'),
  array('ID' => '74','Mr of Mrs' => 'นาย','Name' => 'จกิต','Lastname' => 'สีทองสู้','Class' => '3','Classnumber' => '2','Number' => '4'),
  array('ID' => '75','Mr of Mrs' => 'นาย','Name' => 'บานาลี','Lastname' => 'กาจัยนา','Class' => '3','Classnumber' => '2','Number' => '5'),
  array('ID' => '76','Mr of Mrs' => 'นางสาว','Name' => 'ชิวาลี','Lastname' => 'สมฤดี','Class' => '3','Classnumber' => '2','Number' => '6'),
  array('ID' => '77','Mr of Mrs' => 'นางสาว','Name' => 'ณัตธิดา','Lastname' => 'นามิน','Class' => '3','Classnumber' => '2','Number' => '7'),
  array('ID' => '78','Mr of Mrs' => 'นางสาว','Name' => 'มารี','Lastname' => 'ศรีกุมาร','Class' => '3','Classnumber' => '2','Number' => '8'),
  array('ID' => '79','Mr of Mrs' => 'นางสาว','Name' => 'ชลฤดี','Lastname' => 'สิงห์ทอง','Class' => '3','Classnumber' => '2','Number' => '9'),
  array('ID' => '80','Mr of Mrs' => 'นางสาว','Name' => 'นานา','Lastname' => 'สาทิน','Class' => '3','Classnumber' => '2','Number' => '10'),
  array('ID' => '81','Mr of Mrs' => 'นาย','Name' => 'ทาสานี','Lastname' => 'ทุกข์สุข','Class' => '3','Classnumber' => '3','Number' => '1'),
  array('ID' => '82','Mr of Mrs' => 'นาย','Name' => 'มีสาวี','Lastname' => 'มีทุกวัน','Class' => '3','Classnumber' => '3','Number' => '2'),
  array('ID' => '83','Mr of Mrs' => 'นาย','Name' => 'กานนา','Lastname' => 'ขามี','Class' => '3','Classnumber' => '3','Number' => '3'),
  array('ID' => '84','Mr of Mrs' => 'นาย','Name' => 'ฉัตรชัย','Lastname' => 'มาดีกาล','Class' => '3','Classnumber' => '3','Number' => '4'),
  array('ID' => '85','Mr of Mrs' => 'นาย','Name' => 'พรเทพ','Lastname' => 'เจ้าคงคา','Class' => '3','Classnumber' => '3','Number' => '5'),
  array('ID' => '86','Mr of Mrs' => 'นางสาว','Name' => 'นิลดา','Lastname' => 'ปราถนา','Class' => '3','Classnumber' => '3','Number' => '6'),
  array('ID' => '87','Mr of Mrs' => 'นางสาว','Name' => 'นุสิตรา','Lastname' => 'พราวดี','Class' => '3','Classnumber' => '3','Number' => '7'),
  array('ID' => '88','Mr of Mrs' => 'นางสาว','Name' => 'สุกันยา','Lastname' => 'สินดินดี','Class' => '3','Classnumber' => '3','Number' => '8'),
  array('ID' => '89','Mr of Mrs' => 'นางสาว','Name' => 'ปราณี','Lastname' => 'ทรัพย์พึงมี','Class' => '3','Classnumber' => '3','Number' => '9'),
  array('ID' => '90','Mr of Mrs' => 'นางสาว','Name' => 'กนกวัล','Lastname' => 'ศรีดารา','Class' => '3','Classnumber' => '3','Number' => '10')
);
